### ISSUE TITLE
Missing ResetInterface method

### ISSUE THREAD

**Issue by chyzas** [php-vcr/VCRBundle#12]
PHP Fatal error:  Class VCR\VCRBundle\DataCollector\VCRDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Contracts\Service\ResetInterface::reset) in /home/project/src/vendor/php-vcr/vcr-bundle/DataCollector/VCRDataCollector.php on line 61

**Comment by simonhard** [comment]
We've already had the fix in master. I now created a release. Please take a look at v1.4.2 (https://github.com/php-vcr/VCRBundle/releases/tag/1.4.2)

**Comment by simonhard** [comment]
resolved
